
----1.what is the total number of rows in each of the 3 tables in database?

select * from prod_cat_info
select count(*)
from prod_cat_info

select * from Customer
select count(*)
from customer

select * from Transactions
select count(*)
from Transactions

----2.what is the total number of transactions that have a return?

select count(transaction_id)as count_id
from transactions,prod_cat_info
where qty<0

----3.As you would have noticed, the dates provided across the datasets are not in a correct format.
----As first steps, pls convert the date variables into valid date formats before proceeding ahead.
SOLTN--DONE

----4.What is the time range of the transaction data available for analysis? 
----Show the output in number of days, months and years simultaneously in different columns.

select 
day(tran_date) as day1,
month(tran_date)as month1,
year(tran_date) as year1
from Transactions

----5.Which product category does the sub-category “DIY” belong to?

select (prod_cat) as name
from prod_cat_info
where prod_subcat = 'DIY'
-------------------------------------------------------------------------------------------

----1.Which channel is most frequently used for transactions?

select top 1
store_type,count(store_type) as freqchannel
from transactions
group by store_type
order by freqchannel desc

----2.What is the count of Male and Female customers in the database?

select count(gender) AS MALE
from Customer
WHERE GENDER='M'

SELECT COUNT(GENDER) AS FEMALE
FROM CUSTOMER
WHERE GENDER='F'

----3.From which city do we have the maximum number of customers and how many?

SELECT top 1
city_code,count(city_code) as maxcustmer
from customer
group by city_code
order by maxcustmer desc


----4.How many sub-categories are there under the Books category?

select 
COUNT(prod_subcat) as CNT
from prod_cat_info
where prod_cat = 'Books'

----5.What is the maximum quantity of products ever ordered?

SELECT TOP 1 
Qty,COUNT(QTY) AS MAXNO
FROM TRANSACTIONS
GROUP BY QTY
ORDER BY MAXNO DESC

----6.What is the net total revenue generated in categories Electronics and Books?
 
 select top 2
sum(total_amt) as totrev
from Transactions
where (prod_cat_code = 3 or
		prod_cat_code = 5 )
group by total_amt
order by totrev desc

----7.How many customers have >10 transactions with us, excluding returns?

select cust_id,
count(cust_id) as under10trans
from Transactions
group by cust_id
having count(cust_id)>10
order by under10trans desc

----8.What is the combined revenue earned from the “Electronics” & “Clothing” categories,
------from “Flagship stores”?

select 
sum(total_amt) as totrevEC
from Transactions
where Store_type='flagship store' and
		prod_cat_code = 1 or
		prod_cat_code = 3
group by total_amt
order by totrevEC desc

----9.What is the total revenue generated from “Male” customers in “Electronics” category? 
----Output should display total revenue by prod sub-cat.?

select*
from prod_cat_info oi
join Transactions od
on oi.prod_cat_code=od.prod_cat_code
and oi.prod_sub_cat_code=od.prod_subcat_code
where prod_cat='electronics'
order by od.total_amt desc


----10.What is percentage of sales and returns by product sub category; 
----display only top 5 sub categories in terms of sales?


select top 5 
count(total_amt)/SUM(total_amt)*100 as percentagesales, 
ik.prod_subcat 
from Transactions as pl
INNER JOIN prod_cat_info as ik
ON pl.prod_subcat_code = ik.prod_sub_cat_code
where pl.Qty > 0
group by ik.prod_subcat
order by percentagesales desc




----11.	For all customers aged between 25 to 35 years 
----find what is the net total revenue generated by these consumers in last 30 days 
----of transactions from max transaction date available in the data?
---SOLTN--NOT ABLE TO



----12.Which product category has seen the max value of returns in the last 3 months of
----transactions?

SELECT TOP 1
prod_cat_code,
SUM(Total_amt) as totalreturns
FROM TRANSACTIONS
WHERE Tran_date >= DATEADD(day,-90,'12-06-2012') AND Total_amt < 0
GROUP BY prod_cat_code
ORDER BY totalreturns ASC



----13.Which store-type sells the maximum products; by value of sales amount
----and by quantity sold?

select top 1 store_type,
sum(total_amt) as sales_amt,
sum(Qty) as qty_sold
from Transactions
group by Store_type
order by sales_amt desc,qty_sold desc



----14.What are the categories for which average revenue is above the overall average.

SELECT p.prod_cat, AVG(t.total_amt) AS average 
FROM (SELECT t.*, AVG(t.total_amt) OVER () as overall_average
      FROM Transactions T
     ) t JOIN
     prod_cat_info P 
     ON T.prod_cat_code = P.prod_cat_code
GROUP BY p.prod_cat, overall_average
HAVING AVG(t.total_amt) > overall_average;


----15.Find the average and total revenue by each subcategory for 
----the categories which are among top 5 categories in terms of quantity sold.

select top 5  bm.prod_subcat as pro_SubCat, 
AVG(total_amt) as avgRev,
SUM(total_amt)as totlrev
from Transactions as mn
INNER JOIN prod_Cat_info as bm
ON mn.prod_cat_code = bm.prod_cat_code 
AND mn.prod_subcat_code = bm.prod_sub_cat_code
group by bm.prod_subcat
